[IMP] GH #92 Help attrs for US IDs
LasLabs/vertical-medical pull request #100
Opened 2017-01-13 18:50 UTC by kellylougheed

Adds more helper text about valid input to ID fields.

2017-01-14 00:27 UTC, lasley commented
Looks like lint is failing - https://travis-ci.org/LasLabs/vertical-medical/jobs/191725033#L319

Ignore all the tabs instead of spaces one. I'll actually submit something to fix that all right now.

2017-01-18 00:56 UTC, lasley requested changes

2017-01-18 00:56 UTC, lasley commented on medical_insurance_us/models/medical_insurance_template.py
> +        help='RX BIN Number - six-digit number',
We could also add `size` attributes here if we know the sizes

2017-01-18 00:56 UTC, lasley commented on medical_insurance_us/models/medical_insurance_template.py
> +        help='RX Processor Control Number (PCN) - up to 10 chars',
Switching between numeric and alpha representations of the numbers. I'm indifferent, but pick one and stick with it 😉

2017-01-18 00:56 UTC, lasley commented on medical_medicament_us/models/medical_medicament_ndc.py
> +        help='National Drug Code - 10-digit number',
NDC can be 10 or 11 actually - http://phpa.dhmh.maryland.gov/OIDEOR/IMMUN/Shared%20Documents/Handout%203%20-%20NDC%20conversion%20to%2011%20digits.pdf

2017-01-18 00:56 UTC, lasley commented on medical_patient_us/models/medical_patient.py
> +        help='US Driver\s License - varies by state',
missing an apostrophe after the `\`-  Driver\'s

2017-01-18 00:56 UTC, lasley commented on medical_pharmacy_us/models/medical_pharmacy.py
> +        help='National Boards of Pharmacy Id # - seven-digit number',
Switching between hyphenated and non with `number-digit` vs `number digits`. Again indifferent, but keep it consistent.

2017-01-18 00:56 UTC, lasley commented on medical_pharmacy_us/models/medical_pharmacy.py
> +        help='Medicaid Id # - nine digits and one alpha character',
s/Id/ID

2017-01-18 00:56 UTC, lasley commented on medical_physician_us/models/medical_physician.py
> +        help='''Drug Enforcement Agency # - \
Best to break this string off. Current strategy is adding a bunch of blank whitespace.

```
help='Drug Enforcement Agency # - '
     'two alpha characters and seven digits'
```

2017-01-26 02:52 UTC, lasley commented
@kellylougheed - is this ready for review?

2017-01-26 05:19 UTC, kellylougheed commented
@lasley yes!

2017-01-26 17:34 UTC, lasley commented
@kellylougheed - sweet -so in our repos when something is ready after changes have been made, drop a comment saying so & update the tags. In repos you don't have write access too, the comment should also contain a note for maintainers to update the tag.

2017-01-26 17:35 UTC, lasley approved these changes

2017-01-26 17:35 UTC, merged