[9.0][MIG] Upgrade medical to 9.0.
LasLabs/vertical-medical pull request #11
Opened 2016-09-19 20:06 UTC by bmw95

Man this diff is absolutely massive. The OCA commit history goes up to Jan 30 2016, and any commits between there and now on release/9.0 are all laslabs ones which is nice. Means I can just copy paste the folder.

**Couple things to bring to light:**
* Are the file headers for python and xml correct? Will be using that header on all files for now on if good.
* Is this [help](https://github.com/laslabs/vertical-medical/compare/9.0...laslabs:custom/9.0/LABS-287-medical-v9?expand=1#diff-0180c4fc21f7260dcce8093bf66149ceR47) attribute correct for is_work?
* Does laslabs/9.0 share the same config files as OCA/9.0? I noticed the travis build had less build jobs than usual (compared to release/9.0), so not sure if the travis config file needs to be improved to add stuff.

2016-09-20 16:00 UTC, lasley commented on medical/__openerp__.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Remove our perpetual copyright, also I accidentally deleted some of the original attributions - we will need to fix that.

```
Copyright 2004-2009 Tiny SPRL
Copyright 2016 LasLabs Inc.
```

2016-09-20 16:01 UTC, lasley commented on medical/README.rst
> +This module extends Odoo with the base functionality of medical patients, centers, and doctors.
This module does not provide doctors anymore.

2016-09-20 16:02 UTC, lasley commented on medical/README.rst
> +**Some patient attributes available:**
While we can leave it, it's not necessary to list attributes provided. Concept of patient and medical centers does it. If anything, explain what a medical center or patient is, not what their data looks like.

2016-09-20 16:02 UTC, lasley commented on medical/README.rst
> +`here <https://github.com/OCA/vertical-medical/issues/new?body=module:%20medical%0Aversion:%209.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_
Change this to bug tracker blurb to current template

2016-09-20 16:03 UTC, lasley commented on medical/__init__.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Remove perpetual copyrihgt, add 2004 from Tech-Receptives

2016-09-20 16:03 UTC, lasley commented on medical/__openerp__.py
> +    "author": "LasLabs, Odoo Medical Team, Odoo Community Association (OCA)",
Remove `Odoo Medical Team` - they're not a thing anymore

2016-09-20 16:03 UTC, lasley commented on medical/__openerp__.py
> +    "summary": "Extends Odoo with medical patients, doctors, and centers.",
No doctors

2016-09-20 16:04 UTC, lasley commented on medical/data/ir_sequence_data.xml
> +<!-- Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Remove perpetual copyright

2016-09-20 16:04 UTC, lasley commented on medical/demo/medical_patient_demo.xml
> +<!-- Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Perpetual copyright

2016-09-20 16:06 UTC, lasley commented on medical/demo/medical_patient_demo.xml
> +		<field name="name">Emma Fields</field>
Add ref https://fakena.me/fake-social-security-number/

2016-09-20 16:06 UTC, lasley commented on medical/demo/medical_patient_demo.xml
> +		<field name="name">Kyle Jones</field>
Add ref https://fakena.me/fake-social-security-number/

2016-09-20 16:06 UTC, lasley commented on medical/demo/medical_patient_demo.xml
> +		<field name="name">Gary Smith</field>
Add ref https://fakena.me/fake-social-security-number/

2016-09-20 16:06 UTC, lasley commented on medical/demo/medical_patient_demo.xml
> +		<field name="dob">1980-11-02</field>
let's kill this patient - add `dod`

2016-09-20 16:07 UTC, lasley commented on medical/medical_constants.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Perpetual copyright, add tech-receptives

2016-09-20 16:07 UTC, lasley commented on medical/models/__init__.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Perpetual copyright, add tech-receptives

2016-09-20 16:07 UTC, lasley commented on medical/models/medical_patient.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Perpetual copyright, add tech-receptives

2016-09-20 16:09 UTC, lasley commented on medical/models/medical_patient.py
> +    @api.constrains('is_pregnant', 'gender')
Add `api.multi`

2016-09-20 16:19 UTC, lasley requested changes

2016-09-20 16:22 UTC, lasley commented
@bmw95 - dunno about `is_work` - just leave it, will probably remove in v10. Don't worry about anything outside of the module dir.

2016-09-23 00:23 UTC, bmw95 commented on medical/__openerp__.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Was actually me ;). Wasn't quite sure how to go about that so know now for future.

2016-09-23 00:23 UTC, bmw95 commented on medical/__openerp__.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Done

2016-09-23 00:23 UTC, bmw95 commented on medical/__openerp__.py
> +    "summary": "Extends Odoo with medical patients, doctors, and centers.",
Done

2016-09-23 00:23 UTC, bmw95 commented on medical/__openerp__.py
> +    "author": "LasLabs, Odoo Medical Team, Odoo Community Association (OCA)",
Done

2016-09-23 00:24 UTC, bmw95 commented on medical/README.rst
> +This module extends Odoo with the base functionality of medical patients, centers, and doctors.
Done

2016-09-23 00:25 UTC, bmw95 commented on medical/README.rst
> +**Some patient attributes available:**
Reduced to "This module extends Odoo with the base functionality of medical patients and centers." Removed attribute descriptions.

2016-09-23 00:25 UTC, bmw95 commented on medical/README.rst
> +`here <https://github.com/OCA/vertical-medical/issues/new?body=module:%20medical%0Aversion:%209.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_
Done

2016-09-23 00:32 UTC, bmw95 commented on medical/__init__.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Done

2016-09-23 00:33 UTC, bmw95 commented on medical/data/ir_sequence_data.xml
> +<!-- Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Done

2016-09-23 00:34 UTC, bmw95 commented on medical/demo/medical_patient_demo.xml
> +<!-- Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Done

2016-09-23 00:37 UTC, woodbrettm commented on medical/demo/medical_patient_demo.xml
> +		<field name="dob">1980-11-02</field>
Done

2016-09-23 00:52 UTC, bmw95 commented on medical/medical_constants.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Done

2016-09-23 00:52 UTC, bmw95 commented on medical/models/__init__.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Done

2016-09-23 00:52 UTC, bmw95 commented on medical/models/medical_patient.py
> +# Copyright 2016-TODAY LasLabs Inc. (https://laslabs.com)
Done

2016-09-23 00:54 UTC, bmw95 commented on medical/models/medical_patient.py
> +    @api.constrains('is_pregnant', 'gender')
Done. multi placed first then constrains.

2016-09-23 01:14 UTC, bmw95 commented on medical/demo/medical_patient_demo.xml
> +		<field name="name">Emma Fields</field>
Done

2016-09-23 01:14 UTC, bmw95 commented on medical/demo/medical_patient_demo.xml
> +		<field name="name">Kyle Jones</field>
Done

2016-09-23 01:14 UTC, bmw95 commented on medical/demo/medical_patient_demo.xml
> +		<field name="name">Gary Smith</field>
Done

2016-09-23 08:19 UTC, bmw95 commented
### Changes Made In Addition to Review Requests
*	Add gender to demo patients
*	Refactor tests to use demo data (so much faster now!)
*	Add patient compute_deceased method (with depends on dod)
*	Add tests that cover the following cases:
    * Ensure pregnant female doesn’t raise any ValidationErrors
    * Split age test into 3 separate tests (no dob, deceased, and normal cases)
    * Test deceased is True if dod
    * Test deceased is False if no dod
    * Refactored action_invalidate test

### Thoughts
* Should there be language translations on strings used in the tests if they can be translated in the core logic (e.g. validationerror messages, etc)?
* Was curious if we should add deceased field to the patient view with logic to allow it to be editable. Would allow for rare cases where the patient is deceased but no dod has been confirmed yet.

2016-09-24 07:23 UTC, bmw95 commented
Forgot to change manifest website key to laslabs domain.

2016-09-25 18:26 UTC, lasley approved these changes
This looks good to me, thanks @bmw95 

Regarding your questions:
- Don't worry about the translations, non-issue
- There will never be an instance in the medical field of a non-confirmed date of death. If they are marked as dead, a date will be known

2016-09-25 18:26 UTC, merged