[IMP] medical_prescription_state: Add default states
LasLabs/vertical-medical pull request #119
Opened 2017-01-20 23:24 UTC by lasley

* Add default prescription and prescription line states based on US workflow

This was extracted from never released module medical_prescription_state_us. I feel that having the US workflows in core beats having nothing at all. I am unable to think of a more abstract workflow that doesn't just end up with the same thing we have here.

Depends: 
- [ ] #118

2017-01-20 23:25 UTC, lasley commented
Oops didn't mean to tag as needing review - this is pending #118

2017-01-21 00:35 UTC, tedsalmon commented
Should be good to rebase meow.

2017-01-21 01:51 UTC, lasley commented
Rebased! 🚀

2017-01-21 05:53 UTC, jcdrubay approved these changes
LGTM

2017-01-23 17:09 UTC, kellylougheed commented on medical_prescription_state/data/base_kanban_stage.xml
> +    <record id="prescription_order_state_unverified" model="base.kanban.stage">
Looks like this line is causing an error: "External ID not found in the system: medical.prescription.order" while parsing /home/travis/build/LasLabs/vertical-medical/medical_prescription_state/data/base_kanban_stage.xml:10

2017-01-23 19:31 UTC, lasley commented
References fixed, build should go 🍏  now

2017-01-23 23:25 UTC, tedsalmon requested changes
```
2017-01-23 20:13:06,014 236 WARNING openerp_test odoo.models: base.kanban.stage.create() includes unknown fields: state
```

I believe you're looking for `kanban_status`? https://github.com/OCA/server-tools/blob/9.0/base_kanban_stage/models/base_kanban_abstract.py#L79

2017-01-27 01:37 UTC, lasley commented
Oops yeah that field was part of a test of something else that I didn't end up implementing. Removed!

I'm going to merge assuming build passes.

2017-01-27 02:00 UTC, lasley commented
Dang it doesn't work 😖

2017-01-27 04:13 UTC, lasley commented
Alright this now works & I added a hook to changed any existing prescriptions to the Unverified stage.

Note that there are still some Rxs and Rx Lines in the "Undefined" column, because the modules that installed the demo data for them are not dependent on `_state` & ended up coming afterwards in the load order. This is simply a demo issue, and would work fine in production - as evidenced by the scripts that are in the correct stage because they were in earlier modules.

The only way to fix above is to create glue modules for each of the other modules in order to fix the demo data. Not worth it IMO, both in terms of effort and clunking up module namespaces.

2017-01-27 22:35 UTC, merged