[10.0][IMP] website_medical_prescription_order_line: Upgrade view
LasLabs/vertical-medical pull request #121
Opened 2017-01-26 21:13 UTC by kellylougheed

- Changes prescription table in website_medical_prescription_order_line into responsive prescription cards.

![prescription-cards](https://cloud.githubusercontent.com/assets/18649466/22350583/3ba78a3e-e3c9-11e6-9314-3b535799eec9.png)

2017-01-31 03:32 UTC, lasley requested changes
Thanks @kellylougheed - comments inline.

I think we may also want to switch up to two columns inside the KanBan in order to save some vertical space.

2017-01-31 03:32 UTC, lasley commented on website_medical_prescription_order_line/views/medical_prescription_order_line_template.xml
> +                                <span t-field="line.name" /><br/>
General rule - if you're using a `<br/>`, you're probably doing it wrong. Similar to tables, really. There's a time & a place, but for the most part we design around them.

In this case, I believe encapsulating the label and spans in `<p>` would a slightly better spacing too.
```
<p>
    <label />
    <span />
</p>
```

2017-01-31 03:32 UTC, lasley commented on website_medical_prescription_order_line/views/medical_prescription_order_line_template.xml
> +                                    <span t-field="line.last_dispense_id.date_planned" t-field-options='{"widget": "date"}' />
I don't think we want the date widget here -It's not an editable field. Using it also makes it a block element, so it's on a sep line:

![image](https://cloud.githubusercontent.com/assets/7397578/22451105/79f84990-e720-11e6-92cc-62765c9a6d4f.png)

2017-01-31 03:32 UTC, lasley commented on website_medical_prescription_order_line/views/medical_prescription_order_line_template.xml
>                                          <t t-if="line.id in order_lines_filtered.ids or [line.id] == order_lines_filtered.ids">
Please add a note to readme:
* Refactor around requirement for pre-existing Sale Order for Add to Cart button

2017-01-31 16:35 UTC, kellylougheed commented
Changes made in response to the inline comments @lasley!

2017-02-24 22:18 UTC, woodbrettm approved these changes
LGTM! Checked on my phone as well and looks nice.

2017-02-24 22:18 UTC, bmw95 commented on website_portal_medical_prescription_order_line/views/medical_prescription_order_line_template.xml
> -
Should be an empty line between the odoo tags and the content inside them.
```
<odoo>

    <template, record, etc>

</odoo>
```

2017-02-28 04:50 UTC, kellylougheed commented on website_portal_medical_prescription_order_line/views/medical_prescription_order_line_template.xml
> -
Empty lines added!

2017-02-28 16:43 UTC, lasley approved these changes

2017-02-28 16:43 UTC, merged