[ADD] medical_medicament_storage: Reusable storage instructions
LasLabs/vertical-medical pull request #14
Opened 2016-10-13 23:30 UTC by obulkin

* Add new model for medicament storage instructions
(medical.medicament.storage)
* Add views for manipulating medical.medicament.storage records
* Update the storage field on medical.medicament to use the new storage model
in place of a free-form text field
* Update the form view for medical.medicament to better match the new storage
field
* Add demo data that showcases the new arrangement

2016-10-14 00:00 UTC, lasley commented
Need to add access rules for all new models - https://travis-ci.org/laslabs/vertical-medical/jobs/167508916#L1604

I'd just mimic the ones in medicament

2016-10-14 00:05 UTC, lasley requested changes

2016-10-14 00:05 UTC, lasley commented on medical_medicament_storage/__openerp__.py
> +    'license': 'LGPL-3',
AGPL-3

2016-10-14 00:05 UTC, lasley commented on medical_medicament_storage/models/medical_medicament.py
> +    storage = fields.Many2many(
All *2M fields should end in `_ids`

2016-10-14 00:05 UTC, lasley commented on medical_medicament_storage/models/medical_medicament_storage.py
> +
```
_sql_constraints = [
    ('name_uniq', 'unique (name)', 'Each name must be unique.'),
]
```

2016-10-14 21:07 UTC, obulkin commented on medical_medicament_storage/models/medical_medicament_storage.py
> +
Good call. I didn't realize this was an option.

2016-10-20 15:22 UTC, lasley commented
Thanks @obulkin 

FYI the assignment works great in our repos, but in public repos make sure to drop a "Changes finished" or similar comment in order to ping reviewers.

2016-10-20 15:22 UTC, lasley approved these changes

2016-10-20 15:23 UTC, merged