[9.0][MIG] medical_family: Upgrade to v9 - Fixes #144
LasLabs/vertical-medical pull request #151
Opened 2017-02-10 23:02 UTC by kellylougheed

2017-02-11 23:16 UTC, lasley commented
@kellylougheed - looks like this was targeting 9.0 and not release/9.0. I retargeted, but now there are conflicts. Easiest way to resolve would be to reset local to release/9.0 then cherry pick your 037c677 and force push

2017-02-13 15:58 UTC, kellylougheed commented
Done @lasley

2017-02-13 16:21 UTC, lasley commented
@kellylougheed - Runbot is failing due to warnings

2017-02-13 17:15 UTC, kellylougheed commented
@lasley Runbot errors are the same as on the main release/9.0 branch

2017-02-14 23:10 UTC, lasley requested changes

2017-02-14 23:10 UTC, lasley commented on medical_family/__openerp__.py
> +    'version': '9.0.1.1.0',
We restart our internal semantic versioning on migration, so this would be `9.0.1.0.0`

2017-02-14 23:10 UTC, lasley commented on medical_family/views/medical_family_view.xml
>  <openerp>
`odoo`

2017-02-14 23:10 UTC, lasley commented on medical_family/views/medical_family_view.xml
>          <record id="medical_family_view_tree" model="ir.ui.view">
Please decrease extra tab level

2017-02-14 23:10 UTC, lasley commented on medical_family/views/medical_patient_view.xml
>  <openerp>
`odoo`

2017-02-14 23:10 UTC, lasley commented on medical_family/views/medical_patient_view.xml
>          <record id="medical_patient_view_form" model="ir.ui.view">
Tab level -1

2017-02-15 16:36 UTC, kellylougheed commented
Changes made @lasley

2017-02-15 16:38 UTC, lasley commented on medical_family/views/medical_patient_view.xml
>                                              <a type="open">
Why is this tab level now different?

The process here should have been `CMD+A` then `TAB`

2017-02-15 16:39 UTC, lasley commented on medical_family/views/medical_patient_view.xml
>                                              <a type="open">
Yeah there's a few tab levels in this file now. You will need to revert this change on this file, then perform the above process to change the tab level.

2017-02-15 16:54 UTC, kellylougheed commented
Tabs hopefully fixed now @lasley

2017-02-15 16:55 UTC, lasley commented
Nope

2017-02-15 17:03 UTC, kellylougheed commented
What specifically needs to change @lasley? I did the keyboard shortcuts you suggested, and all the tabs are 4 spaces as far as I can tell.

2017-02-15 17:06 UTC, lasley commented
Oh actually sorry, the remainder is just due to an additional `<t>` that didn't used to exist, so was causing the diff to look not edited in two spots. We're good now thanks!

2017-02-15 17:07 UTC, lasley approved these changes

2017-02-16 21:37 UTC, woodbrettm requested changes
Couple things:
* Missing [static/description/icon.png](https://github.com/OCA/maintainer-tools/blob/master/template/module/static/description/icon.png)
* Copyright headers need to be fixed. For example something like: (in python)
````
# -*- coding: utf-8 -*-
###############################################################################
#
#    Tech-Receptives Solutions Pvt. Ltd.
#    Copyright (C) 2004-TODAY Tech-Receptives(<http://www.techreceptives.com>)
#    Special Credit and Thanks to Thymbra Latinoamericana S.A.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
````

Should be changed to:
````
# -*- coding: utf-8 -*-
# Copyright 2004 Tech-Receptives Solutions Pvt. Ltd.
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
````

If there's multiple licenses in the file, list the `Copyright <date> <company_name>` by date, oldest at the top. (perhaps newest should be at the top. hrmmm. I've been doing oldest at top but you could argue either or).

2017-02-16 21:37 UTC, woodbrettm commented on medical_family/README.rst
>  For further information, please visit:
* Remove

Also:
* Missing Images section under Credits header
* Bug Tracker section needs to be updated
* Remove double entry of Parthiv Patel in contributors, as well as double entry of Dave Lasley. Don't forget to add your name as well if you want :)
* Update Maintainer section
* template here: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2017-02-16 21:37 UTC, woodbrettm commented on medical_family/README.rst
>  .. image:: https://img.shields.io/badge/license-AGPL--3-blue.svg
```rst
.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
   :target: http://www.gnu.org/licenses/agpl-3.0-standalone.html
   :alt: License: AGPL-3

```

2017-02-16 21:37 UTC, bmw95 commented on medical_family/__openerp__.py
> +    'version': '9.0.1.0.0',
This file should follow the same structure as [this](https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py). The end result will be the same structure/organization as this one I keep on hand with me. All double quotes as well.
````python
{
    "name": "Odoo Medical",
    "summary": "Extends Odoo with medical patients, doctors, and centers.",
    "version": "9.0.1.0.0",
    "category": "Medical",
    "website": "https://laslabs.com",
    "author": "LasLabs, Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": [
        "base",
        "product",
    ],
    "data": [
        "data/ir_sequence_data.xml",
        "security/medical_security.xml",
        "security/ir.model.access.csv",
        "views/medical_patient_view.xml",
        "views/res_partner_view.xml",
        "views/medical_menu.xml",
    ],
    "demo": [
        "demo/medical_patient_demo.xml",
    ],
}

2017-02-16 21:37 UTC, bmw95 commented on medical_family/views/medical_family_view.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Should be an empty line between headers and xml code. This should normally be something like:
````xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright 2016-2017 LasLabs Inc.
     License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl). -->

<odoo>
    . . .
````
however there's no license holder specified here originally so the xml version tag by itself is fine.

2017-02-17 16:19 UTC, lasley commented
Oldest at top IMO. It takes significantly more effort to write software than it does to upgrade it. It's about a 5:1 ratio in my exp

2017-02-17 23:04 UTC, bmw95 commented
Ah that makes sense. That way the writers get the most recognition. Thanks for pointing that out didn't think of that.

2017-02-18 01:56 UTC, kellylougheed commented
Changes made @bmw95! Although unfortunately some of your comments may have disappeared -- I had to reset the branch to release/9.0 (it wouldn't let me rebase since I had branched off 9.0, not release/9.0) and cherry-pick.

2017-02-18 06:39 UTC, tedsalmon approved these changes
LGTM now :) 👍

2017-02-18 08:01 UTC, woodbrettm approved these changes

2017-02-18 16:48 UTC, merged

2017-02-23 18:25 UTC, lasley commented
@kellylougheed - please use format-patch & submit these changes to OCA/9.0. 9.0 is done on LasLabs incubator for the most part, so we should be submitting things to OCA.