Fixes #134 - Adds autofocus to medical_medicament
LasLabs/vertical-medical pull request #156
Opened 2017-02-11 21:51 UTC by kellylougheed

Adds autofocus to medical_medicament and makes "Medicaments" the first tab open when the user is creating a new medicament.

2017-02-11 23:25 UTC, lasley requested changes
The `autofocus` should be on the page instead of the field. Also, there should be no need to change the notebook order, we just need to select the page

2017-02-13 17:01 UTC, kellylougheed commented
Accidentally squashed my last commit in a reset, but done @lasley

2017-02-13 18:32 UTC, lasley approved these changes

2017-02-17 17:28 UTC, tedsalmon approved these changes
👍 LGTM!

2017-02-17 17:28 UTC, merged