[ADD] medical_medicament_us/website_sale_medical_medicament_us: Brand/generic IDs and links
LasLabs/vertical-medical pull request #16
Opened 2016-10-25 01:24 UTC by obulkin

* Add the computed fields brand_ids and generic_ids to medical.medicament,
which return all of the brand-name and generic medicaments with the same GCN
as the medicament in question, including itself
* Add unit tests for the methods used to compute the new fields
* Extend the website_sale.product template to add links to brand-name
medicament shop pages that point to equivalent generics and vice versa. These
are based on the brand_ids and generic_ids fields on medical.medicament
* Add demo data that showcases the change

2016-10-25 01:48 UTC, lasley commented
Travis is failing on lint

2016-10-25 18:09 UTC, lasley requested changes

2016-10-25 18:09 UTC, lasley commented on website_sale_medical_medicament_us/README.rst
> +
Missing Runbot link

2016-10-25 18:09 UTC, lasley commented on website_sale_medical_medicament_us/__openerp__.py
> +    'installable': True,
Add `'auto_install': True`. This forces install as long as all dependencies are installed, which is desired for the US modules

2016-10-25 18:11 UTC, lasley commented on medical_medicament_us/models/medical_medicament.py
> +            record.brand_ids = self.env['medical.medicament'].search([
`self.search`

2016-10-25 18:11 UTC, lasley commented on medical_medicament_us/models/medical_medicament.py
> +            record.generic_ids = self.env['medical.medicament'].search([
`self.search`

2016-10-25 18:13 UTC, lasley commented on website_sale_medical_medicament_us/demo/medical_medicament.xml
> +        <field name="name">Tylenol</field>
Make this another brand

2016-10-25 18:13 UTC, lasley commented on website_sale_medical_medicament_us/demo/medical_medicament.xml
> +        <field name="strength">600</field>
GCNs are unique per strength, so this is invalid data. Switch to 300 and change the brand

2016-10-25 23:13 UTC, lasley commented
You need to add some security. Log out, then go to a product page using this feature.

You can't access the Runbot logs after initial test, so I paste below:

```
QWebException: (u'Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:\n- Accounting & Finance/Medical Assistant\n\t- Accounting & Finance/Medical Doctor\n\t- Accounting & Finance/Medical User\n\n(Document model: medical.medicament.gcn)', None)
```

2016-10-26 20:02 UTC, obulkin commented
Good catch. I should get in the habit of testing things out when I'm not logged in as admin.

2016-10-26 21:14 UTC, obulkin commented
I combined my latest change with the last two PR commits and then remembered that I should instead just add more. My bad. It shouldn't be too annoying here since there's only one change to review.

2016-10-31 19:16 UTC, lasley approved these changes

2016-10-31 19:16 UTC, merged