Fixes #141 - error installing website_pricelist_medical_insurance
LasLabs/vertical-medical pull request #161
Opened 2017-02-14 00:36 UTC by kellylougheed

- Corrects the inherited view.
- Revises the product_pricelist model so that it doesn't crash when you go to a pricelist.

2017-02-14 23:16 UTC, lasley requested changes

2017-02-14 23:16 UTC, lasley commented on website_pricelist_medical_insurance/views/website_pricelist_view.xml
>          <record id="website_pricelist_form_view" model="ir.ui.view">
Decrease tab level. XML is 4 spaces per namespace for a tab, similar to Python.

2017-02-16 20:28 UTC, bmw95 commented
Module installs fine for me, however I get a lot of logs like this in a very short period of time when installing (could be from medical_insurance instead). Not sure if that's an issue or not : |

````
2017-02-16 20:14:29,807 2139 INFO test werkzeug: 127.0.0.1 - - [16/Feb/2017 20:14:29] "GET /shop/product/e-com06-custom-computer-kit-12?page=2 HTTP/1.1" 200 -
2017-02-16 20:14:29,809 2139 INFO test odoo.addons.website.tests.test_crawl: demo /shop/product/pcsc234-computer-sc234-9?page=2
2017-02-16 20:14:29,837 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,840 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,882 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,884 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,912 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,915 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,919 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,921 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,931 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,933 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,950 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,952 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,984 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:29,987 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:30,021 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:30,024 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:30,027 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
2017-02-16 20:14:30,029 2139 INFO test odoo.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 5, model: medical.insurance.template
````

2017-02-17 16:29 UTC, lasley commented
@bmw95 - I think that's your local. I do not see the output you are referring to in any CI logs

2017-02-17 20:33 UTC, lasley approved these changes

2017-02-17 20:33 UTC, merged