[IMP] medical_prescription_sale_crm: Improve to match oca specs.
LasLabs/vertical-medical pull request #163
Opened 2017-02-14 16:34 UTC by lasley

* Rename module to sale_crm_medical_prescription
* Remove unnecessary logging
* Change rec_id to record in loops
* Add usage instructions to readme
* Remove commented code
* Fix crm_lead_view attr overrides
* Add demo data
* Reorganize manifest
* Fix copyrights in headers
* Add oca icon to description
* Fix readme to match oca template
* Remove splitting by customer and rx_line

Forward port of OCA#88

2017-02-16 19:33 UTC, woodbrettm requested changes
Found a few things but other than that LGTM!

Missing [test_medical_lead_wizard file](https://github.com/OCA/vertical-medical/blob/9.0/sale_crm_medical_prescription/tests/test_medical_lead_wizard.py).

2017-02-16 19:33 UTC, bmw95 commented on sale_crm_medical_prescription/wizards/medical_lead_wizard.py
> -from collections import defaultdict
Still need this (used in action_create_leads)

2017-02-17 18:19 UTC, lasley commented
@bmw95 - test_medical_lead_wizard is already [on the incubator & doesn't look to be changed](https://github.com/LasLabs/vertical-medical/blob/release/10.0/sale_crm_medical_prescription/tests/test_medical_lead_wizard.py)

2017-02-17 18:22 UTC, lasley commented
Oh actually I take that back, I just ran the diff. Weird wonder how I missed that.. I'll rerun the filter just to make sure I didn't miss something else too

2017-02-17 20:47 UTC, lasley commented
Alright I redid the filter & it looks better now

2017-02-17 23:01 UTC, woodbrettm approved these changes

2017-02-17 23:02 UTC, bmw95 commented
Thanks @lasley looks much better now :)

2017-02-17 23:34 UTC, tedsalmon requested changes
Tests failing and a couple of points that need to be addressed.

2017-02-17 23:34 UTC, tedsalmon commented on sale_crm_medical_prescription/wizards/medical_lead_wizard.py
> +from openerp import api, fields, models
Should be `odoo` as this PR targets 10.0

2017-02-17 23:34 UTC, tedsalmon commented on sale_crm_medical_prescription/wizards/medical_lead_wizard.py
> +                'name': ', '.join(rx_order.name for rx_order in rx_orders),
The test for this method is failing because of the order of `rx_orders`. Perhaps you could `rx_orders.sorted(key=lambda r: r.name)`?

2017-03-11 08:38 UTC, bmw95 commented
@tedsalmon updated.

2017-03-13 22:58 UTC, tedsalmon approved these changes
LGTM! 👍

2017-03-13 22:58 UTC, merged