[10.0] [REM] [IMP] Deprecate medical_base_history and update medical_appointment accordingly
LasLabs/vertical-medical pull request #171
Opened 2017-02-17 02:13 UTC by obulkin

[REM] medical_base_history
* Remove module, which was only used in ``medical_appointment`` and has been
deprecated in favor of ``auditlog``

[IMP] medical_appointment
* Fix broken ``medical.appointment`` unit test
* Remove all uses of deprecated module ``medical_base_history`` from manifest as
well as ``medical.appointment`` model and associated data files/views
* Add ``auditlog`` dependency and data file with ``auditlog.rule`` record for tracking
``medical.appointment`` changes
* Update ``medical.appointment`` to inherit from ``mail.thread`` for added tracking
and messaging functionality
* Update ``medical_appointment_view_form`` to show new ``mail.thread`` fields
* Remove comments field from ``medical.appointment`` model and associated data
files/views

2017-02-17 16:18 UTC, lasley commented
@obulkin - tests are failing

2017-02-17 22:57 UTC, obulkin commented
@lasley --- It's due to the ``auditlog`` dependency not being met: ``module medical_appointment: Unmet dependencies: auditlog``, possibly because it's in a different repo. How do I address that?

2017-02-18 02:28 UTC, lasley commented
It's not merged yet right? You'll need to update the [oca_dependencies.txt](https://github.com/LasLabs/vertical-medical/blob/release/10.0/oca_dependencies.txt#L2)

2017-02-18 03:12 UTC, jcdrubay commented
Auditlog is not available in v10 in oca: https://github.com/OCA/server-tools

But I just noticed that you did the migration on your server tools: https://github.com/LasLabs/server-tools/tree/10.0-mig-auditlog

oca_dependencies.txt should probably look like this:

```
partner-contact
# Waiting on merge of OCA/website#270
website https://github.com/laslabs/website.git release/10.0/website_field_autocomplete_related
server-tools https://github.com/laslabs/server-tools.git 10.0-mig-auditlog
```

Sorry for not following on that myself earlier  :/ and thanks for continuing :)

2017-02-19 15:51 UTC, lasley commented
@obulkin - Auditlog was merged today, so no need to change oca_dependencies. I have restarted the builds.

2017-02-21 01:01 UTC, lasley requested changes
@obulkin - Comment inline + please fix the warnings.

2017-02-21 01:01 UTC, lasley commented on medical_appointment/data/medical_appointment_data.xml
>  <openerp>
`<odoo>` tag. Also the two data tags can be removed to combine the sections - they're both noupdate=0

2017-02-23 23:48 UTC, obulkin commented
@lasley - I've pushed up a commit that addresses your comment and the Runbot warnings.

2017-02-24 01:04 UTC, tedsalmon approved these changes
Approved pending minor changes requested. LGTM otherwise!

2017-02-24 01:04 UTC, tedsalmon commented on medical_appointment/tests/medical_appointment.yml
>      email: arun@example.com
File contains DOS line endings. Could you fix? This should do it for you in OS X:
```
perl -pe 's/\r\n|\n|\r/\n/g' medical_appointment.yml > medical_appointment.yml.fix && mv medical_appointment.yml.fix medical_appointment.yml
```

2017-02-24 01:04 UTC, tedsalmon commented on medical_appointment/views/medical_menu.xml
> +<odoo>
Space between Odoo and `menuitem`'s, please

2017-02-28 16:48 UTC, lasley commented
@tedsalmon - Oleg has been taking some classes, so may not be able to make the change in reasonable timeframe. Please just do yourself

2017-03-01 22:59 UTC, obulkin commented
Thanks for pushing up the fix, @tedsalmon. I think this is ready for merge now, @lasley.

2017-03-02 00:06 UTC, lasley approved these changes

2017-03-02 00:06 UTC, merged