Fixes #132 - medical_appointment: Makes date, time, and duration required
LasLabs/vertical-medical pull request #174
Opened 2017-02-23 01:28 UTC by kellylougheed

- Makes medical_base_history installable so that medical_appointment can also be installed
- Makes the date/time of the appointment and the duration required fields so that they don't throw the errors noted in #132 
- Clarifies that the duration refers to minutes (it wasn't intuitive to me)

2017-02-23 02:43 UTC, lasley commented
@kellylougheed - please see #71

2017-02-23 02:48 UTC, kellylougheed commented
@lasley do you want me to expand this PR to also implement Kanban stages for medical_appointment?

2017-02-23 02:57 UTC, lasley commented
Oops sorry #171

2017-02-23 03:02 UTC, kellylougheed commented
@lasley OK, that looks awesome. Should I do a forward port of that PR and just throw in the required fields? Or would it be easier to include the required fields in that PR?

2017-02-23 16:44 UTC, lasley commented
Let's include the required fields in that PR

2017-02-23 17:46 UTC, kellylougheed commented
@lasley OK, should I push to that PR myself or leave it to @obulkin?

2017-02-23 18:18 UTC, lasley commented
You can just push the fix yourself

2017-02-23 18:28 UTC, kellylougheed commented
Done @lasley -- although when I pulled the branch, it created an extra "merge" commit. Hopefully it will be squashed?

2017-02-23 18:42 UTC, lasley commented
You added a lot more than just a merge commit. There are a lot more commits in that PR now, most of which don't involve the PR.

2017-02-23 19:06 UTC, obulkin commented
K. I just cleaned up #171 with a force push :jedi:. Maybe we should rebase this branch onto ``feature/10.0/LABS-379-deprecate-medical_base_history`` and make this PR dependent on #171?

2017-02-23 19:23 UTC, lasley commented
Sounds like a plan @obulkin

2017-03-02 20:05 UTC, obulkin commented
@kellylougheed - #171 has been merged now, so you can resolve the conflicts and get this ready for review.

2017-03-05 22:27 UTC, kellylougheed commented
Thanks @obulkin!

2017-03-06 19:17 UTC, lasley commented on medical_appointment/models/medical_appointment.py
>          default=30.0,
Add a `digits`, with a decimal precision specific for appointment times.

https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/l10n_fr_hr_payroll/models/l10n_fr_hr_payroll.py#L11

https://github.com/odoo/odoo/blob/fc2e80cb4bcc450762c7ac5cb82a3e2d88062b38/addons/hr_payroll/data/hr_payroll_data.xml#L82

2017-03-07 16:21 UTC, kellylougheed commented
Decimal precision added @lasley

2017-03-07 16:47 UTC, lasley commented on medical_appointment/data/medical_appointment_data.xml
> +    <record forcecreate="True" id="decimal_appointment" model="decimal.precision">
Essentially all files need to be split by model, the same way we do with actual models. See [contribution docs, file naming](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#file-naming)

2017-03-08 17:42 UTC, kellylougheed commented
Created a new file for the decimal precision data @lasley

2017-03-08 18:15 UTC, lasley requested changes
The XML needs to be declared in manifest

2017-03-08 18:15 UTC, lasley commented on medical_appointment/data/decimal_precision_data.xml
> +
Too many newlines

2017-03-08 18:15 UTC, lasley commented on medical_appointment/data/decimal_precision_data.xml
> +    <record forcecreate="True" id="decimal_appointment" model="decimal.precision">
order is id, model, other stuff

also id should be `model_name_something`

2017-03-08 19:19 UTC, kellylougheed commented
File changed @lasley

2017-04-10 22:44 UTC, merged