[10.0][IMP] Forward Ports
LasLabs/vertical-medical pull request #180
Opened 2017-03-02 17:11 UTC by lasley

This ports some changes over that have been merged into OCA/9.0

2017-03-06 18:33 UTC, tedsalmon requested changes
There are tests failing. Some are because `napb_num` is still being referenced in views even after this field was changed to the proper name, `nabp_num`.

The other test failure is due to a broken assertion:
```
odoo.addons.medical_medicament.tests.test_medical_medicament: `   File "/home/travis/build/LasLabs/vertical-medical/medical_medicament/tests/test_medical_medicament.py", line 65, in test_active_component_ids
odoo.addons.medical_medicament.tests.test_medical_medicament: `     len(active), 1
odoo.addons.medical_medicament.tests.test_medical_medicament: ` AssertionError: 0 != 1
```

2017-03-06 18:33 UTC, tedsalmon commented on medical_family/__manifest__.py
> +    'version': '9.0.1.0.0',
10.0

2017-03-06 18:33 UTC, tedsalmon commented on medical_family/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/159/9.0
10.0

2017-03-06 18:33 UTC, tedsalmon commented on sale_crm_medical_prescription/__openerp__.py
> +    "version": "9.0.1.0.0",
10.0

2017-04-29 03:00 UTC, bmw95 commented
@LasLabs/admins I performed a diff audit on this PR and the following was changed:

#### Dropped: Changes already present in release/10.0 (or better code)
* sale_crm_medical_prescription
* Convert all product_uom grams to units (except strength_uoms)

#### Moved
* medical_family port to: #195
* medical_prescription_us port to: #196

#### Current Changes Left
* Missing medical_pharmacy_view and medical_medicament_view in sale_medical_prescription manifest
* Version bumps
* Making rx_line name readonly
* Some copyright stuff

2017-05-11 15:53 UTC, lasley commented
I'm unclear as to the status of this PR review

2017-05-11 18:55 UTC, tedsalmon approved these changes

2017-05-11 18:56 UTC, tedsalmon commented
Yeah, a lot has changed since I last looked at this, apparently. Anyways, LGTM!

2017-05-11 18:57 UTC, merged