[10.0][IMP] medical_prescription_state_verify: Add support for verification procedures
LasLabs/vertical-medical pull request #185
Opened 2017-03-16 03:03 UTC by kellylougheed

Work in progress -- tests not yet passing.

- Forward port of #173 
- Automatically moves prescription lines with a verified prescription to the "Hold" stage
- Allows prescription lines to be modified by moving them to the "Hold" stage even if the parent prescription is verified
- If a prescription is verified, the prescription line cannot be modified otherwise (e.g. moved back to "Unverified")

2017-04-10 23:01 UTC, lasley requested changes

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state/data/base_kanban_stage.xml
> +        <field name="is_verified" eval="True" />
This should be in the _verified module

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state/models/base_kanban_stage.py
> +    is_verified = fields.Boolean(
This should be in the _verify module

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order.py
>      _ALLOWED_CHANGE_KEYS = ['stage_id', ]
Remove stray `, `

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order.py
> +    _ALLOWED_CHANGE_STATES = ['Verified', 'Cancelled', 'Exception', ]
Remove stray `, `

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order.py
>          for rec_id in self:
`self.filtered(lambda r: r.stage_id.is_verified)` & remove below conditional

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order.py
> +            if rec_id.stage_id.is_verified:
This is outside of the record loop, but using the record. It's also causing two db writes & performing the same conditional twice. All the logic should be moved above & injected into vals before write.

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order.py
> +                for prescription_order_line in \
`\` is nasty hack.

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order_line.py
> +    _name = 'medical.prescription.order.line'
This is superfluous unless you are inheriting multiple models at once.

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order_line.py
> +        if self.prescription_order_id.stage_id.is_verified:
Expects singleton. Write requires a record loop

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order_line.py
> +                if stage_id.name == "Hold":
Using the name of a stage will not be future proof to user edits. There should be an option on the stage to allow it to be moved to after verification.

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order_line.py
> +                    return super(
This logic nesting is too complex.

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order_line.py
> +                self.prescription_order_id.name
The string interpolation should be outside of the translation - you don't want to translate the interpolation. `_('text %s') % var`

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/tests/test_medical_prescription_order.py
> +        prescription_order_line_id = self.env.ref(
remove _id suffix, this is a recordset

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/tests/test_medical_prescription_order.py
> +        record_id.write({'stage_id': 4})  # verified
Hard coded database Ids should be replaced for XML ref

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/tests/test_medical_prescription_order_line.py
> +        self.order_id.stage_id = 4  # verified
Hard coded db ids

2017-04-10 23:01 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order_state.py
> -    type = fields.Selection([
Why is this removed?

2017-04-10 23:01 UTC, lasley commented on sale_crm_medical_prescription/tests/test_crm_lead.py
> +        for id in [patient.id]:
I think this can be simplified

2017-04-10 23:01 UTC, lasley commented
@bmw95 - please take this over

2017-05-31 19:15 UTC, obulkin commented
This PR has been replaced by #213, so I'm closing it.

2017-05-31 19:15 UTC, closed without merging