[10.0][IMP] website_portal_medical_prescription_order_line: Add 'Expired' and 'Out of Refills' labels
LasLabs/vertical-medical pull request #187
Opened 2017-03-22 19:40 UTC by kellylougheed

- Adds 'Expired' and 'Out of Refill labels when applicable to prescription order lines on "My Medical"
![screen shot 2017-03-22 at 11 59 16 am](https://cloud.githubusercontent.com/assets/18649466/24217330/ba0134a8-0efc-11e7-9702-0de1501c1543.png)
- Adds a computed is_expired field to medical_prescription_order_line

2017-03-28 15:52 UTC, lasley requested changes

2017-03-28 15:52 UTC, lasley commented on website_portal_medical_prescription_order_line/models/medical_prescription_order_line.py
> +            stop = datetime.datetime.strptime(
`fields.Datetime.from_string`

2017-03-28 15:52 UTC, lasley commented on website_portal_medical_prescription_order_line/models/medical_prescription_order_line.py
> +    @api.one
`api.one` is deprecated. Use `api.multi` & record loop

2017-03-28 15:52 UTC, lasley commented on website_portal_medical_prescription_order_line/models/medical_prescription_order_line.py
> +        for record in self:
You already have the record loop. This wasn't needed with api.one, which loops for you. But it's deprecated.

2017-03-28 15:52 UTC, lasley commented on website_portal_medical_prescription_order_line/models/medical_prescription_order_line.py
> +                record.is_expired = True
`record.is_expired = stop and stop < now`

2017-03-28 15:52 UTC, lasley commented on website_portal_medical_prescription_order_line/models/medical_prescription_order_line.py
> +            if stop and stop < datetime.datetime.now():
`.now()` should be computed before the record loop & assigned to variable for reuse

2017-03-28 22:39 UTC, kellylougheed commented
Changes made @lasley

2017-03-28 22:57 UTC, lasley requested changes

2017-03-28 22:57 UTC, lasley commented on website_portal_medical_prescription_order_line/models/medical_prescription_order_line.py
> +            stop = fields.Datetime.from_string(self.date_stop_treatment)
s/self/record

2017-03-28 22:57 UTC, lasley commented on website_portal_medical_prescription_order_line/models/medical_prescription_order_line.py
> +            now = datetime.datetime.now()
Move this outside the record loop

2017-03-28 23:59 UTC, lasley commented on website_portal_medical_prescription_order_line/models/medical_prescription_order_line.py
> +    is_expired = fields.Boolean(
This should be moved into medical_prescription

2017-03-29 15:02 UTC, kellylougheed commented
Changes made @lasley

2017-03-29 16:19 UTC, lasley approved these changes

2017-03-29 16:20 UTC, merged