[10.0][FIX] medical_center and medical_physician
LasLabs/vertical-medical pull request #198
Opened 2017-05-01 00:57 UTC by bmw95

* Fix parent_id field in medical_center
* Add primary_center and secondary_centers to medical_physician

2017-05-11 15:51 UTC, lasley requested changes

2017-05-11 15:51 UTC, lasley commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
This should not be renamed

2017-05-11 15:51 UTC, lasley commented on medical_physician/views/medical_physician_view.xml
> +                <field name="medical_center_primary_id" />
Why is parent_id removed?

2017-05-11 15:51 UTC, lasley commented on medical_physician/views/medical_physician_view.xml
> +                    <field name="medical_center_primary_id"
Why is parent_id removed?

2017-05-11 19:32 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
I'm not sure I follow. Renamed from what?

2017-05-11 20:00 UTC, lasley commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
The existing medical center concept was not supposed to be changed. I believe it used to be parent_id

2017-05-11 21:03 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
ah I see. So I guess this should be removed, and then just have something like `secondary_parent_ids` for the other field?

2017-05-11 21:14 UTC, lasley commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
`medical_center_ids`, compute and store. Make computation dependent on `parent_id`. Ensure that the `parent_id`'s medical center record is added in when `parent_id` is changed. Keep in mind, parent will be a partner so it lacks the medical context.

2017-05-16 02:42 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
@lasley is the compute function only to add in the parent_id to medical_center_ids? Or is there something else that needs to be added to medical_center_ids as?

Should I also add an inverse function to the field as well?

2017-05-16 03:00 UTC, lasley commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
Yes it is just to add the parent_id into medical_center_ids.

Inverse is not needed if it's stored.

2017-05-16 20:22 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
@lasley you want the field to be editable though right? Or just readonly?

2017-05-16 20:25 UTC, lasley commented on medical_physician/models/medical_physician.py
> +    medical_center_primary_id = fields.Many2one(
It needs to be editable

2017-05-16 23:06 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
So I added a compute method for `medical_center_ids` with this section here. What's really weird is whenever I change `parent_id` in the UI, `medical_center_ids` is completely emptied and this single center record is added. Any ideas as to why that may be?

2017-05-16 23:09 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
Oh actually no I think this bit is working. However I think what happens is when the compute function is triggered, the field is completely emptied of the records before running code in the compute method. I'm not exactly sure what to do in that case.

2017-05-16 23:19 UTC, lasley commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
Why aren't you using the ORM methods?

2017-05-16 23:19 UTC, lasley commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
`[(4, center.id)]`

2017-05-16 23:45 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
I tried that but get the following error:
```
2017-05-16 23:35:29,118 24933 INFO physician odoo.sql_db: bad query:  INSERT INTO medical_center_medical_physician_rel (medical_physician_id, medical_center_id)
                        (SELECT a, b FROM unnest('{}') AS a, unnest(ARRAY[1]) AS b)
                        EXCEPT (SELECT medical_physician_id, medical_center_id FROM medical_center_medical_physician_rel WHERE medical_physician_id IN ())

2017-05-16 23:35:29,118 24933 ERROR physician odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 5469, in onchange
    newval = record[name]
  File "/opt/odoo/odoo/models.py", line 5177, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/fields.py", line 870, in __get__
    self.determine_draft_value(record)
  File "/opt/odoo/odoo/fields.py", line 988, in determine_draft_value
    self._compute_value(record)
  File "/opt/odoo/odoo/fields.py", line 926, in _compute_value
    getattr(records, self.compute)()
  File "/media/sf_odoo10dev/vertical-medical/medical_physician/models/medical_physician.py", line 63, in _compute_medical_center_ids
    'medical_center_ids': [(4, center.id)],
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 275, in write
    result = super(MailThread, self).write(values)
  File "/opt/odoo/odoo/models.py", line 3545, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/models.py", line 3661, in _write
    field.write(self.with_context(rel_context), vals[name])
  File "/opt/odoo/odoo/fields.py", line 2376, in write
    link([act[1]])
  File "/opt/odoo/odoo/fields.py", line 2346, in link
    cr.execute(query, (records.ids, list(sub_ids), tuple(records.ids)))
  File "/opt/odoo/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 3: ...nter_medical_physician_rel WHERE medical_physician_id IN ())
```

The code I have is as follows:
```python
    @api.multi
    @api.depends('parent_id')
    def _compute_medical_center_ids(self):
        for record in self:
            center = self.env['medical.center'].search([
                ('partner_id', '=', record.parent_id.id),
            ], limit=1)

            if not center:
                continue

            if center not in record.medical_center_ids:
                record.write({
                    'medical_center_ids': [(4, center.id)],
                })
```

2017-05-17 02:23 UTC, lasley commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
Try uninstalling mail_thread_medical_prescription

2017-05-17 03:18 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
I already had that module uninstalled sadly :(

2017-05-17 03:29 UTC, lasley commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
`medical.physician` needs to inherit from `mail.thread`. But this should already be the case by its inheritance of the [abstract.entity](https://github.com/LasLabs/vertical-medical/blob/release/10.0/medical/models/medical_abstract_entity.py#L15). Try directly inheriting as a test

2017-05-17 03:32 UTC, lasley commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
Wait actually that's not it. When are you getting this error?

2017-05-17 04:14 UTC, bmw95 commented on medical_physician/models/medical_physician.py
> +                record.medical_center_ids += center
I get that error whenever I change the parent_id in the physician form view. Adding centers to the medical_center_ids field works in the form though.

2017-06-21 23:52 UTC, bmw95 commented
@lasley removed physician changes. Good to go.

2017-06-22 03:40 UTC, lasley approved these changes

2017-06-22 03:41 UTC, merged