[ADD][10.0] Add brand/generic links to medicaments in US
LasLabs/vertical-medical pull request #21
Opened 2016-10-31 19:30 UTC by lasley

Direct forward port of #16

2016-10-31 22:33 UTC, tedsalmon requested changes
@lasley,

Please update the manifest file to reflect version 10.x

```
website_sale_medical_medicament_us/__openerp__.py:5: [C8106(manifest-version-format), ] Wrong Version Format "9.0.1.0.0" in manifest file. Regex to match: "(10.0)\.\d+\.\d+\.\d+"
```

2016-10-31 22:41 UTC, lasley commented
Oops forgot the migration commit. Migrated

2016-11-01 00:16 UTC, tedsalmon approved these changes

2016-11-01 00:17 UTC, t3ddftw commented
Looks good now :)

2016-11-01 00:17 UTC, merged