Rx State Verification - Bug fixes and redesign
LasLabs/vertical-medical pull request #213
Opened 2017-05-31 19:12 UTC by obulkin

[10.0][FIX] ``medical_prescription_state``: Move field and duplicate record
* Move ``base.kanban.stage`` field ``is_verified`` to child module ``medical_prescription_state_verify``
* Replace second occurrence of the ``prescription_order_state_exception`` record with ``prescription_order_line_state_exception``, an equivalent stage intended for the ``medical.prescription.order.line`` model

[10.0][FIX] ``medical_prescription_state_verify``: Move field
* Move ``base.kanban.stage`` field ``is_verified`` from parent module ``medical_prescription_state``

[10.0][IMP] ``medical_prescription_state_verify``: Redesign
* Update ``base.kanban.stage`` records introduced in ``medical_prescription_state`` to be verified where needed
* Rework verification-related logic in ``medical.prescription.order`` and ``medical.prescription.order.line``
* Add demo data and unit tests for new logic
* Update README and manifest

2017-05-31 19:15 UTC, obulkin commented
This PR is meant to replace #185 and #211.

2017-06-06 19:55 UTC, lasley requested changes
Few minor changes

2017-06-06 19:55 UTC, lasley commented on medical_prescription_state_verify/README.rst
> +* When a prescrption order moves from an unverified state to a verified one,
s/prescrption/prescription

2017-06-06 19:55 UTC, lasley commented on medical_prescription_state_verify/models/medical_prescription_order.py
> +                else:
You can actually remove this else and eliminate a tad of complexity. The raise is like a return - code execution stops at that point, thus the else is superfluous

2017-06-07 18:26 UTC, lasley commented
@obulkin - please squash the last three commits into one for merge. I can't do an auto-squash here due to the two modules.

2017-06-07 19:43 UTC, obulkin commented
@lasley - The branch is squashed now and ready for a merge.

2017-06-08 04:24 UTC, lasley approved these changes

2017-06-08 04:25 UTC, merged

2017-06-08 04:25 UTC, lasley commented
Thanks Oleg!