[ADD] medical_prescription_merge: Rx order merging
LasLabs/vertical-medical pull request #24
Opened 2016-11-03 03:28 UTC by obulkin

* Add medical.prescription.order.merge wizard model with logic for merging any
number of existing prescription orders into one and various validations
related to this process. Users select a destination order whose info takes
precedence when there are conflicts and can choose to skip certain validations.
* Add a form view, a menu item, and an action for the wizard model

2016-11-03 03:33 UTC, obulkin commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +        # domain='[("id", "in", merge_order_ids[0][2])]',
@lasley - As per our convo earlier, the wizard should only allow users to select a destination order that is in the merge order list. The domain shown here will do that, but you decided that it was too hacky and wanted to look into it further as part of the PR review.

2016-11-08 20:54 UTC, lasley requested changes

2016-11-08 20:54 UTC, lasley commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +        if self.env.context.get('active_model') \
`\` is a nasty hack, use an intermediary var instead

```
        active_model = self.env.context.get('active_model')
        if active_model == 'medical.prescription.order':
```

2016-11-08 20:54 UTC, lasley commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +                == 'medical.prescription.order':
`rx_model = 'medical.prescription.order'` and remove all the duplicate strings

2016-11-08 20:54 UTC, lasley commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +                self.env.context.get('active_ids')
Another place that intermediary var would help

2016-11-08 20:54 UTC, lasley commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +        if merge_order_ids:
Better to ask forgiveness than permission:
```
        try:
            return self._compute_default_merge_orders()[0]
        except (IndexError, TypeError):
            return
```

2016-11-08 20:54 UTC, lasley commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +            merge_physicians = set(self.merge_order_ids.mapped('physician_id'))
Move this into a method of its own `_do_validation` or similar. Allows for inherited modules to inject logic. Rule of thumb, logic in loops is inaccessible to downstream modules. This definitely should be accessible.

2016-11-08 21:20 UTC, lasley requested changes

2016-11-08 21:20 UTC, lasley commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +    def _compute_default_merge_orders(self):
_default_merge_orders

2016-11-08 21:20 UTC, lasley commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +    def _compute_default_dest_order(self):
_default_dest_order

2016-11-08 21:21 UTC, lasley commented
@obulkin all your's

2016-11-08 22:03 UTC, lasley commented
Oops it seem my push failed. Now it's all your's

2016-11-09 20:14 UTC, obulkin commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +            merge_physicians = set(self.merge_order_ids.mapped('physician_id'))
Sure thing. There are no loops happening here, but all the same, the code doesn't provide a way for child classes to overload the validations, and I definitely see the value in that.

2016-11-09 20:25 UTC, lasley commented on medical_prescription_merge/wizards/medical_prescription_order_merge.py
> +            merge_physicians = set(self.merge_order_ids.mapped('physician_id'))
Oops I meant to say control structure, not loop. Logic in control structures is inaccessible. Sounds like you got that though 😄

2016-11-14 20:18 UTC, lasley approved these changes

2016-11-14 20:18 UTC, merged