[FIX] Replace openerp with odoo
LasLabs/vertical-medical pull request #258
Opened 2017-12-03 13:34 UTC by App-247

2017-12-04 21:52 UTC, lasley commented
Thanks for the submission @App-247 

@obulkin - can you please review and see to it that the changes also make their way to OCA?

2017-12-05 20:25 UTC, obulkin requested changes
Thanks for the submission, @App-247. I've made a few minor comments in line.

Also, OCA guidelines require a separate commit per affected module, so we may not be able to preserve attribution when porting this over to the OCA repo unless you rebase your branch accordingly.

2017-12-05 20:25 UTC, obulkin commented on medical/models/medical_patient.py
> +        ('S', 'Never Married'),
Please leave all of the old selection keys in place for backward compatibility. The values can be modified as needed for greater alignment with FHIR, and new options are definitely welcome.

2017-12-05 20:25 UTC, obulkin commented on medical_medicament_attribute/views/medical_medicament_attribute_type_view.xml
> +    The license is in the file __odoo__.py
The v10 equivalent of ``__openerp__.py`` is ``__manifest__.py``. However, if you're gonna update these at all, I would instead suggest just switching over to the latest OCA copyright format, which can be found [here](https://github.com/OCA/maintainer-tools/blob/master/template/module/data/model_name_data.xml#L2). The module is licensed under LGPL-3.0.

2017-12-05 20:25 UTC, obulkin commented on medical_physician/views/medical_specialty_view.xml
> +</odoo>
There needs to be a newline character here.

2017-12-05 20:25 UTC, obulkin commented on medical_physician/wizard/medical_physician_unavailable_view.xml
> +</odoo>
Ditto on the newline.

2017-12-05 22:14 UTC, lasley commented
Hey @App-247 - I just looked in the OCA instance and I can't find a CLA for you. Is this your first contribution to an OCA project?

2017-12-05 22:19 UTC, App-247 commented
Yes. I had forgotten. Right now I do it.

2018-01-29 22:30 UTC, lasley commented
Hi @App-247 - there was a DMCA in this repo and I'm having to close this PR because it's based on offending code.

We're moving to the OCA rep, so it would be best to just submit the change there.

2018-01-29 22:30 UTC, closed without merging