[IMP] medical: Simplify models
LasLabs/vertical-medical pull request #34
Opened 2016-11-12 02:04 UTC by lasley

Second commit performs necessary upgrade regexes to all downstream modules. Much easier than a PR a piece, seeing as it's all dependent. 

[IMP] medical: Simplify models  …
* Add `partner_contact_birthdate`, `partner_firstname`, and `partner_identification` dependencies
* Remove attributes in partner and patient that are duplicated by dependencies
* Remove is_* attributes on partner in favor of `type`
* Act upon type to create medical entities automatically from partner if of correct type

[FIX] Fix medical.patient.dob references  …
* Change `dob` to `birthdate_date` for compatibility with `partner_contact_birthdate`

This is dependent on:
- [ ] OCA/partner-contact#315

2016-11-16 00:41 UTC, lasley commented
OMFG it works. Ready for review!

2016-11-20 21:57 UTC, tedsalmon requested changes
There's a test that needs changing and is causing the build to fail. I also committed a change to fix a broken demo data reference. 😄 

EDIT: Additionally, there are a large number of .py files that are having their mode altered to `100755` 😢

2016-11-20 21:57 UTC, t3ddftw commented on medical_prescription/tests/test_medical_prescription_order.py
> +            self.rx_6.active,
`medical_prescription_prescription_order_6` has no `prescription_order_line_ids` which according to medical_prescription/models/medical_prescription_order.py:_compute_active results in the RX being `active=True`

2016-11-21 22:55 UTC, lasley commented
Test fixed

2016-11-22 04:02 UTC, merged