[ADD][10.0] medical_app_pharmacy
LasLabs/vertical-medical pull request #44
Opened 2016-11-22 03:18 UTC by lasley

* Create app to provide contextual menus for pharmacies

Depends:
- [ ] #34

2016-11-22 04:14 UTC, lasley commented
Rebased; ready for review

2016-11-22 07:35 UTC, tedsalmon requested changes
Tests are failing

```
"External ID not found in the system: medical_app_pharmacy.medical_patient_action" while parsing /home/travis/build/laslabs/vertical-medical/medical_app_pharmacy/views/pharmacy_menu.xml:22, near
<menuitem id="medical_patient" name=" Patient" parent="medical_patient_root" sequence="10" action="medical_patient_action"/>
```
Additionally, there is this warning:
```
2016-11-22 04:51:25,804 5354 WARNING openerp_test odoo.modules.module: module pharmacy: module not found
```

2016-11-22 17:25 UTC, lasley commented
Oops I don't think I meant to remove WIP tag from this. This is definitely not done - SMD needs to provide input

2017-02-18 22:31 UTC, bmw95 commented on medical_app_pharmacy/__manifest__.py
> +# -*- coding: utf-8 -*-# Copyright 2016 LasLabs Inc.# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).{    'name': 'Medical Apps - Pharmacy',    'version': '10.0.1.0.0',    '
No newline and some odd character issues.

2017-08-08 00:26 UTC, obulkin commented
I've addressed the comment by @bmw95 and made a number of other small improvements and fixes. This PR should now be ready for another round of review.

2017-08-08 01:36 UTC, lasley commented
LGTM thanks Oleg

2017-08-08 01:36 UTC, merged