[IMP] medical_patient_disease_allergy: Forward port
LasLabs/vertical-medical pull request #48
Opened 2016-11-30 18:29 UTC by lasley

Forward port OCA#73

* Fix readme to match oca template
* Fix copyright in headers
* Fix view ids
* Reorganize attributes in manifest
* Add demo data
* Refactor tests to use demo data
* Remove svg icon
* Remove maintainer attribute from manifest
* Fix attribute alignment in medical_patient_view

2016-11-30 19:00 UTC, tedsalmon requested changes
CIs are failing. Comments inline.

2016-11-30 19:00 UTC, t3ddftw commented on medical_patient_disease_allergy/__manifest__.py
> +    "summary": "Isolates allergies from diseases.",
Duplicates line 7

2016-11-30 19:00 UTC, t3ddftw commented on medical_patient_disease_allergy/demo/medical_patient_demo.xml
> +        <field name="dob">1999-11-02</field>
This field is now `birthdate_date` after #43 was accepted.

2016-11-30 19:00 UTC, t3ddftw commented on medical_patient_disease_allergy/demo/medical_patient_demo.xml
> +        <field name="gender">m</field>
Gender `m` is invalid, according to tests.

2016-11-30 19:01 UTC, lasley commented on medical_patient_disease_allergy/demo/medical_patient_demo.xml
> +        <field name="gender">m</field>
Indeed it is, `male` now

2016-11-30 19:03 UTC, lasley commented on medical_patient_disease_allergy/__manifest__.py
> +    "summary": "Isolates allergies from diseases.",
I did this in an amend of the original commit, because it was an eff up in my conflict resolution and should not be part of the migration commit

2016-11-30 19:04 UTC, lasley commented
Problems solved! Interestingly enough I had already done them but I guess the push timed out. My baddddd

2016-11-30 19:20 UTC, tedsalmon commented on medical_patient_disease_allergy/tests/test_medical_patient.py
>          self.assertEquals(
This assertion is coming back with partner_5 being active still :/

2016-12-10 00:04 UTC, lasley commented
@t3ddftw - `action_invalidate` logic is also contained in dependency `medical_disease`, so I removed it from here and called it a day.

2016-12-12 23:24 UTC, tedsalmon approved these changes

2016-12-12 23:26 UTC, t3ddftw commented
Runbot is errored out but:
```
Module test summary
[1;32mSuccess[0;m 
```
Seems like a false positive.

@lasley, is coverage drop the cause for the runbot being errored out? If so, what's up with the -0.1% drop in coverage?

Other than that, looks good to me!

2016-12-13 00:13 UTC, lasley commented
@t3ddftw - coverage drop is in another module that's not really tested. The tests I deleted must have also covered it on accident - https://coveralls.io/builds/9217298/source?filename=website_medical_patient%2Fmodels%2Fmedical_patient.py

We'll nail that in the migrations

2016-12-13 16:57 UTC, merged