[FIX][10.0] medical_prescription_thread to mail_thread_medical_prescription
LasLabs/vertical-medical pull request #56
Opened 2016-12-13 01:16 UTC by lasley

Name change for release branch as mentioned in https://github.com/OCA/vertical-medical/pull/141#pullrequestreview-12583601

2016-12-13 16:56 UTC, tedsalmon requested changes
Seems tests are failing due to a constraint violation on `mail_followers_mail_followers_res_partner_res_model_id_uniq`

2016-12-13 19:10 UTC, lasley commented
Ahhh seems thats a conflict with the prescription merge module & it's being introduced by new alphabetic ordering. I disabled the module and will create a ticket soon assuming I remember 😛

2016-12-14 00:38 UTC, tedsalmon approved these changes

2016-12-14 00:39 UTC, t3ddftw commented
Merging as I assume the coverage drop is due to the due to disabling that module. CI's all look good now :)

2016-12-14 00:39 UTC, merged