[FIX] GH #90 - Rx Creation Errors
LasLabs/vertical-medical pull request #97
Opened 2017-01-12 22:45 UTC by kellylougheed

2017-01-14 01:10 UTC, lasley requested changes

2017-01-14 01:10 UTC, lasley commented on medical_patient_us/models/res_partner.py
> +    @api.constrains('country_id', 'ref')
You would also want `type` in this constrains, because it is part of the validation

2017-01-17 06:51 UTC, tedsalmon approved these changes
Changes LGTM 👍

2017-01-17 09:44 UTC, jcdrubay approved these changes
LGTM @lasley should you move fast on this one?

2017-01-17 17:05 UTC, lasley approved these changes

2017-01-17 17:05 UTC, merged